### ISSUE TITLE
Invalid JPEG Segment at offset 31926 

### ISSUE THREAD

**Issue by tinganho** [mozilla-b2g/exif-parser#5]
I got this error Invalid JPEG Segment at offset 31926
![screen shot 2014-03-20 at 12 43 22 pm](https://f.cloud.github.com/assets/1324476/2469008/33b5d648-afea-11e3-93b2-db5fa9e21d1d.png)

**Comment by hfiguiere** [comment]
I get these with files generated by FirefoxOS on a Flame.... Will work on it.

**Comment by hfiguiere** [comment]
And no the second image doesn't have an invalid Exif. Just that the tool I was using has a bug (fixed).

**Comment by hfiguiere** [comment]
Note that I filed Issue #10 for the second image linked in this bug, because there actually was one.

**Comment by hfiguiere** [comment]
merged
